version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: inventaire-backend
    ports:
      - "5000:5000"
    networks:
      - inventaire-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: inventaire-frontend
    ports:
      - "8081:80"
    networks:
      - inventaire-net
    depends_on:
      - backend

networks:
  inventaire-net:
    driver: bridge
